# YOLO object detection model (weak: yolov8n.pt; medium: yolov8m.pt; strong: yolov8nx.pt)
yolo_model: yolov8n.pt
target_classes: ["person"]
bb_color: [0, 255, 0]
draw_labels: True
conf_threshold: 0.1

# Traffic camera stream information.
fps: 15
width: 1280
height: 720
cycle_time_secs: 60 # If multipe cameras are available.

# Uncomment to enable switching between cameras. See more cameras in `all_cameras.txt`
traffic_cam_url:
  - https://61e0c5d388c2e.streamlock.net/live/3_Stewart_NS.stream/chunklist_w1559207018.m3u8
  - https://61e0c5d388c2e.streamlock.net/live/Aurora_N_145_EW.stream/chunklist_w48234066.m3u8 
  - https://61e0c5d388c2e.streamlock.net/live/LCW_NE_137_NS.stream/chunklist_w1826072949.m3u8
  - https://61e0c5d388c2e.streamlock.net/live/Greenwood_N_125_EW.stream/chunklist_w126395193.m3u8
  - https://61e0c5d388c2e.streamlock.net/live/LCW_NE_125_EW.stream/chunklist_w929818080.m3u8
  # - https://61e0c5d388c2e.streamlock.net/live/Aurora_N_117_NS.stream/chunklist_w1723281647.m3u8
