# Traffic camera stream information
traffic_cam_url: https://61e0c5d388c2e.streamlock.net/live/3_Stewart_NS.stream/chunklist_w1559207018.m3u8
fps: 15
width: 1280
height: 720

# YOLO object detection model (weak: yolov8n.pt; medium: yolov8m.pt; strong: yolov8nx.pt)
yolo_model: yolov8n.pt # currently only `yolov8n.pt` is supported due to latency.
target_classes: ["person"]
bb_color: [0, 255, 0]
draw_labels: True
conf_threshold: 0.1
